/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '5/14/22, 9:40 AM' 
 * Generated by 'u59444488' 
 * Generated on server 'ODAWS01-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-06%253A00&ticket=ST-17474-Ly1ntedHJDMW1RLeoHSG-cas' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.IMPORT1 out=Work.SortTempTableSorted;
	by Internet_Banking E_Statements Bill_Pay Mobile_Banking;
run;

/* Exploring Data */
proc univariate data=Work.SortTempTableSorted;
	ods select Histogram;
	var Age;
	histogram Age;
	by Internet_Banking E_Statements Bill_Pay Mobile_Banking;
run;

proc delete data=Work.SortTempTableSorted;
run;